package rozkladbot.enums;

public enum UserState {
    AWAITING_GREETINGS,
    UNREGISTERED,
    AWAITING_INSTITUTE,
    AWAITING_FACULTY,
    AWAITING_COURSE,
    AWAITING_GROUP,
    AWAITING_REGISTRATION_DATA_CONFIRMATION,
    IDLE,
    MAIN_MENU,
    AWAITING_TODAY_SCHEDULE,
    AWAITING_TOMORROW_SCHEDULE,
    AWAITING_THIS_WEEK_SCHEDULE,
    AWAITING_NEXT_WEEK_SCHEDULE
}
