package rozkladbot.enums;

public enum UserState {
    AWAITING_GREETINGS,
    UNREGISTERED,
    AWAITING_INSTITUTE,
    AWAITING_FACULTY,
    AWAITING_COURSE,
    AWAITING_GROUP,
    IDLE,
    AWAITING_THIS_WEEK_SCHEDULE,
    AWAITING_NEXT_WEEK_SCHEDULE
}
